### ISSUE TITLE
Can't see contact's profile pic

### ISSUE THREAD

**Issue by Geebow** [stonesam92/ChitChat#27]
I'm not able to see my contact's profile pic except 1/2 groups one's.
How can i solve?

**Comment by stonesam92** [comment]
Is this fixed in ChitChat 1.3? Profile pictures should work fine.

If not, can you please include a screenshot?

**Comment by Geebow** [comment]
![schermata 2015-09-03 alle 12 36 25](https://cloud.githubusercontent.com/assets/13612490/9656428/859d904e-5238-11e5-9ad5-699e6d9fe0f1.png)
Downloaded the last version but the problem still there! Hope that we can find a solution 'cause this app it's awesome!
