### ISSUE TITLE
Shortcuts doesn't work anymore

### ISSUE THREAD

**Issue by danielfigueroa** [stonesam92/ChitChat#92]
I recently noticed that shortcuts for moving through the conversations list stopped working. Does anyone knows what happened? Is it something with Web Whatsapp? Only works Cmd + N (new conversation) and Cmd + F (find conversation)

**Comment by MWYang** [comment]
+1

**Comment by danielfigueroa** [comment]
Fixed worked for me, thanks!

**Comment by MWYang** [comment]
@danielfigueroa, does scrolling through conversations with up/down arrow work for you? It still doesn't work for me.

**Comment by danielfigueroa** [comment]
Yes @MWYang  everything works fine. up/down arrows and Cmd + Number. Using version 1.3
